### ISSUE TITLE
Getting this error on startup, forecast never loads

### ISSUE THREAD

**Issue by suiciety** [bremor/bom_forecast#24]
I'm on Home Assistant 0.109.6 HaOS version and would love to get this up and running but get the error below.

Cheers

[homeassistant.components.sensor] Error while setting up bom_forecast platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bom_forecast/sensor.py", line 241, in setup_platform
    bom_forecast_data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/bom_forecast/sensor.py", line 421, in update
    ftp.retrbinary('RETR ' + self._product_id + '.xml', file_obj.write)
  File "/usr/local/lib/python3.7/ftplib.py", line 442, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/local/lib/python3.7/ftplib.py", line 399, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/local/lib/python3.7/ftplib.py", line 365, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/usr/local/lib/python3.7/ftplib.py", line 273, in sendcmd
    return self.getresp()
  File "/usr/local/lib/python3.7/ftplib.py", line 246, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Failed to open file.

**Comment by danpowell88** [comment]
also getting the same

**Comment by extremedavo** [comment]
Have a look in sensor.py for the valid locations - Note that not all are in there, so you might have to pick the closest one.
